### ISSUE TITLE
Example recipe for external libraries

### ISSUE THREAD

**Issue by sean-parent** [QuantStack/xeus-cling#167]
I work on a couple of open source libraries such as https://github.com/stlab/libraries

I would like to make the library available via conda (on conda-forge?) to be installed so it can be used by xeus-cling. Is there an example recipe for this? Docs? Convention (like a github tag) for finding other such libraries?

**Comment by gouarin** [comment]
@sean-parent we already have multiple examples which make what you want.

You can find the recipes we use here : https://github.com/QuantForge

It's always the same way to make a conda-forge package: you have a recipe directory where you set your dependencies and the information of your package in the `meta.yml` file. Then you have to describe how to build and to install your library in `build.sh` (for linux and macOS) and `bld.bat` (for windows).

To load your library directly in xeus-cling you can add these lines in one of your hpp files

https://github.com/QuantStack/xplot/blob/b1f46c5ea89bda457c040f3108bb93c5346b407f/include/xplot/xplot_config_cling.hpp.in#L12

For CI, you just have to modify the names and the configuration you want in

- `appveyor.yml` for windows
- `.travis.yml` for macOS
- `.circleci/config.yml` and `ci_support/run_docker_build.sh` for linux

If you have trouble, you can join the gitter channel https://gitter.im/QuantStack/Lobby

Hope it helps.

**Comment by SylvainCorlay** [comment]
Hey @sean-parent sorry for responding so late to that issue.

Regarding the installation of libraries for usage in `cling`, I would say that the main idea is that ideally, libraries to be used with `cling` should be installed in the same prefix as cling itself. Default include and library search directories will then be correct. 

(A good way to achieve that in the case where `xeus-cling` was installed with a package manager is to use the same manager to install your packages, so if you make use of our package, use conda. At the moment, due to some limitations of conda-forge wrt modern compilers, we use a separate channel for our libraries but it should be merged into conda-forge eventually.)

Now, if your packages require loading libraries, a good way to do this is to make use of the cling pragmas `#pragma cling add_library_path` and `#pragma cling load` so that a user including the library headers will get the runtime loaded automatically. Since the pragma is specific to cling, it won't affect other users of the package. You may be interested in the details of the implementation of that dynamic loading in `xtensor-blas`. You will see that the cling pragmas are passed arguments that are set at installation time by cmake. To not force cmake to our users, we placed them in a separate header that is only included in the case of cling. I think that it is a good pattern to apply for other libraries. https://github.com/QuantStack/xtensor-blas/blob/master/include/xtensor-blas/xblas_config_cling.hpp.in

If you want to make your package available with the quick-help feature (like `?std::vector`), we have detailed the process of registering your package here: http://xeus-cling.readthedocs.io/en/latest/inline_help.html. Again, placing the files in the right configuration directory can be done at installation time.
