### ISSUE TITLE
Strange Error while defining main function

### ISSUE THREAD

**Issue by tommytim0515** [QuantStack/xeus-cling#270]
Some error occurred while defining main function:
```c++
#include <iostream>
using namespace std;

int main() {
    return 0;
}
```
And error was:
```
input_line_8:3:12: error: function definition is not allowed here
int main() {
           ^
Interpreter Error: 
```

My OS is Ubuntu 19.10

**Comment by JohanMabille** [comment]
you don't need to define a main function, the code you're typing in the notebook is already considered as in a kind of a main function (kind of because you can define new functions and classes while is would not be possible in a classical main function). So just type your code and execute it ;)

Also try to put the include statements in a dedicated cell with nothing else than include statements (otherwie you may get this error even when defining a function different from main).
