### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by mariusvniekerk** [QuantStack/xeus-cling#51]
Having a docker image built would make it a lot simpler to deploy this kernel in environments where it doesn't yet work easily (osx etc)

**Comment by SylvainCorlay** [comment]
Thanks. We are working on a conda package and a miniconda-like distribution for os-x, windows and linux that would be self contained!

Then putting together such a docker image for e.g. binder will be fairly trivial!

**Comment by mariusvniekerk** [comment]
Looking forward to it

**Comment by SylvainCorlay** [comment]
@mariusvniekerk the xeus-cling kernel runs in the following binder (which is based on a docker image).

See link below:

[![Binder](https://img.shields.io/badge/launch-binder-brightgreen.svg)](https://beta.mybinder.org/v2/gh/QuantStack/xeus-cling/0.0.6?filepath=notebooks/xcpp.ipynb)

**Comment by SylvainCorlay** [comment]
PS: we also have binders for the xwidgets and xplot projects now.

**Comment by Roboticom314** [comment]
@SylvainCorlay  How would you pull the docker image or retrieve the dockerfile from the binder instance?

**Comment by pelson** [comment]
@Roboticom314 - looks like this isn't possible (https://github.com/jupyterhub/binderhub/issues/619).
Since installation of xeus-cling is so simple with conda, creating a Dockerfile will also be reasonably simple if it itself uses conda (dependencies are in [environment.yml](https://github.com/QuantStack/xeus-cling/blob/master/environment.yml)).


FWIW If you want to produce an image in exactly the same way as is done for the binder instance of this repo, you can also just repo2docker it:

```
jupyter-repo2docker https://github.com/QuantStack/xeus-cling
``` 

Obviously, building the image locally isn't *exactly* the same as using the existing image on mybinder, but the link above does suggest that this isn't possible yet. The only action I can see that may be outstanding on this issue then is to publish images independently such that docker users can quickly install xeus-cling without need for conda and Unix.

@SylvainCorlay - there is an example of doing exactly this in https://github.com/binder-examples/continuous-build if you wanted such functionality.

**Comment by SylvainCorlay** [comment]
I am closing this since xeus-cling has been properlly packaged for conda-forge and a docker image can be easily created now.
