### ISSUE TITLE
install breaks Jupyter -- libzmq.so.5.1.2 not found

### ISSUE THREAD

**Issue by bjpcjp** [QuantStack/xeus-cling#74]
Using Ubuntu 14.04 LTS on Lenovo notebook. I followed the Conda install instructions as shown in the README. Subsequent "jupyter notebook" immediately fails. Here's the error msgs:

    > cannot find -lpthread
    > connot find -lc
    > collect2: error: ld returned 1 exit status
    > ... stack trace ...
    > ImportError: libzmq.so.5.1.2: cannot open shared object file: No such file or directory

**Comment by gouarin** [comment]
Could you send your list of packages installed with conda?

The output of the following command

`conda list`

**Comment by SylvainCorlay** [comment]
@bjpcjp thanks for opening the issue. FYI, in the mean time, you can already experiment with `xeus-cling` without installing anything by clicking on the "launch binder" badge in the readme.

**Comment by bjpcjp** [comment]
Thanks @SylvainCorlay - I had to remove/reinstall Anaconda & Jupyter to make progress on other projects. (Sorry!) I can close this ticket & re-open if I can repeat the behavior. What do you think?

**Comment by SylvainCorlay** [comment]
@bjpcjp no problem. I have a good idea of what might be going on: the cling c++ interpreter is really picky with respect to binary compatibility. This is why our conda channel has builds for libzmq etc..

A good way to install xeus-cling & co is to start from an **empty miniconda** and do

```cpp
conda install xeus-cling notebook -c QuantStack
```

If you start from a regular anaconda installation (instead of a miniconda), it already has libzmq, built with a too old compiler but with the same version number, and conda does not update it with a QuantStack build.

**Comment by bjpcjp** [comment]
@SylvainCorlay Got it. Thanks a lot!
