### ISSUE TITLE
pip install from PyPI into virtualenv

### ISSUE THREAD

**Issue by postrational** [QuantStack/xeus-cling#80]
This is a feature request for:

`pip install xeus-cling`

I would love to use xeus-cling without Conda by simply installing it from PyPI into a virtualenv.

**Comment by SylvainCorlay** [comment]
@postrational, thanks for posting here.

pip is a package installer for Python.

`xeus-cling` involves no Python whatsoever, so it probably does not make sense to make a package for Pypi.

In the mean time, you can certainly have a `miniconda` only holding the `xeus-cling` kernel, and install this kernel into the already existing notebook installation.

Soon, we will be releasing a simple installer for `xeus-cling`, that will simply put things in the directory of your choice.

**Comment by postrational** [comment]
There are many users of Jupyter, who are not using Conda as part of their workflow.

For those users (like me) the installation flow is to create a Python virtualenv and `pip install` Jupyter and other packages.

It would be great to be able to: `pip install jupyter xeus-cling`, start the jupyter server and immediately create a C++ notebook.

I think it would make sense to create a PyPI package for xeus-cling to enable that type of installation.

**Comment by SylvainCorlay** [comment]
I think that you are confused. It is just as if you were asking for a ruby or an npm package for cling.

The python virtual environment has no impact for binary packages like xeus.

We made a conda package because conda is a general-purpose package manager just like Debian's apt-get. conda and Jupyter may be written in Python, but xeus has no relationship to Python whatsoever.

**Comment by postrational** [comment]
I may be mistaken, I'm not exactly clear about how Jupyter kernels are installed. 

If I understand correctly, xeus-cling requires Jupyter to work.  Some people install Jupyter using `pip install jupyter`, so providing a way to install xeus-cling the same way would provide a very nice user experience. 

The fact that xeus-cling is not written in Python is not a key consideration. If Jupyter was installed using npm, then an npm package for xeus-cling would be a good idea also.

**Comment by SylvainCorlay** [comment]
I see where you are coming from. I will post a detailed answer in a few. I am a bit swamped right now.

**Comment by SylvainCorlay** [comment]
So, the Jupyter notebook server happens to be written in Python, but it is mostly an implementation detail. The fact that it comes with a kernel installed as a package in the same python interpreter is more of a convenience.

Jupyter can launch kernels for any language, or even other Python installations in your system. For example, you can have a Jupyter installation at the system level (i.e. in Python 2 or 3.x), and a Python 3.6 kernel installed elsewhere in your system (i.e. a conda installation). All you need for the jupyter installation to be aware of the kernels available.

You can make Jupyter aware of a kernel by installing a `kernel spec` json file with the command

`jupyter kernelspec install /path/to/kernel/spec/file`.

This kernel spec contains the information require for Jupyter to be able to launch the kernel, i.e. the executable that implements the communication protocol.

The C++ kernel is not at all implemented in Python, and is not a Python package. It has really large dependencies like LLVM or Clang.

***
What you can do, is install a miniconda, and the xeus-cling package in that miniconda installation. Refuse to change the `PATH` variable so that the Python that comes with miniconda (as a dependency of conda itself) is not your default Python.

Then you install the kernel spec in your main  jupyter installation
***

**Comment by postrational** [comment]
> What you can do, is install a miniconda, and the xeus-cling package in that miniconda installation. Refuse to change the PATH variable so that the Python that comes with miniconda (as a dependency of conda itself) is not your default Python. 
>
> Then you install the kernel spec in your main jupyter installation

That doesn't sound like the optimal user experience.

`pip install xeus-cling` sounds like a better user experience.

**Comment by bastianl** [comment]
@SylvainCorlay I agree that it doesn't make much sense to install the xeus-cling kernal via pip, but it would be nice to be able to install the kernal without the conda environment.

**Comment by rsemenoff** [comment]
I see in my notes made in my jupyter notebook hosted on windows 10 Chrome, that both !pip install and !conda install can be invoked in a cell, so as someone almost completely new to Jupyter, the method of installation is not the point of complexity at all. The sorts of issues that come to my mind are more like how portable will the c++ I develop in Jupyter be to other compilers like say LLVM for example. The installation process is not the rabbithole I'm worried about so much.

**Comment by kraeml** [comment]
I agree with bastianl. I use apt, npm, gem and pip. Because I use Linux, nodejs, ruby and Python. Why I have to use a whole miniconda system?

**Comment by JohanMabille** [comment]
apt => your language agnostic, distribution dedicated package manager
npm => dedicated to javascript packages
gem => dedicated to ruby packages
pip => dedicated to python packages

Would you agree if I say that asking a Python project to provide packages for npm and gem would not really make sense? That's the same here, the problem being C++ does not have a dedicate package manager. Besides, since we develop some libraries in C++ with bindings to Python, R, and Julia for different platforms, a multi-platform,  language agnostic package manager such as conda was a perfect suit.

As @SylvainCorlay said before, you don't necessarily have to use a whole miniconda system, you can just install it as a package manager for installing xeus-cling (just like you install npm, pip, or any language specific package manager).

Once the stack is more stable we'll provide a installer for xeus cling.

**Comment by kraeml** [comment]
The thing with apt and co is all right. That with C++ I have understood. Thats the reason why I personally use Python. I personally will not use C/C++. I have to install Xeus on Pi3 for my colleague using C/C++. I'm a teacher and not a full stack administrator.

If your project will need npm, and ruby things. Yes I will install it. I Install jupyter (pip), node-red (npm) install php (apt), nginx (apt), ansible(pip) and inspec, cucumber, selenium (ruby) and other things. Because I use this tools in my lessons. So I can handle this and setup a Pi3 for WebDev and DevOps/Sec for me and my students.

I run to some error with miniconda (and also anaconda) last year. So I decided to use them not. The concept of conda is confusing me.

So I agree with bastianl. 

> @SylvainCorlay I agree that it doesn't make much sense to install the xeus-cling kernal via pip, but it would be nice to be able to install the kernal without the conda environment.

**Comment by kraeml** [comment]
@JohanMabille 
May you can help me to install xeus on pi3 herer: https://github.com/QuantStack/xeus-cling/issues/98

Thanks

**Comment by madhavajay** [comment]
Can anyone comment on the difference between Xeus-Cling and https://github.com/root-project/cling

The cling project says it has jupyter kernel support?

**Comment by SylvainCorlay** [comment]
> Can anyone comment on the difference between Xeus-Cling and https://github.com/root-project/cling
>
> The cling project says it has jupyter kernel support?

xeus-cling uses the cling interpreter but not their implementation of the kernel.

The kernel shipped with cling is a "wrapper" kernel, that is, a python program capturing the text output of the interpreter and redirecting them to the Jupyter frontned. It makes use of the implementation of the protocol of ipykernel.

The xeus-cling kernel is a pure C++ implementation making use of cling as a *library* instead of only redirecting the text output. It makes use of the xeus library which is a native implementation of the protocol. The benefits are numerous: we don't need python in the kernel, we support richer interaction with the interpreter, enabling things such as live help, rich display, interactive widgets, magics.

Also, we discuss a lot with the cling team, and we don't see this as a competition. The same goes for ipykernel, of which I am a contributor.

**Comment by madhavajay** [comment]
cling is already on brew though:
$ brew install cling

**Comment by SylvainCorlay** [comment]
Then it should not be too hard to package xeus-cling for brew.

**Comment by SylvainCorlay** [comment]
Closing this issue, which was about a pip package. I am opening another about the discussion on brew packaging.
